name: Build Docker image

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:

  schedule:
    - cron: '25 15 * * *'
  #push:
    #paths-ignore:
      #- "README.md"
    #branches: [ "main" ]
    # Publish semver tags as releases.
    #tags: [ 'v*.*.*' ]
  #pull_request:
    #branches: [ "main" ]
  workflow_dispatch:

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}
  # Xray latest version
  #XRAY_VERSION: v26.3.27


jobs:
  build:

    runs-on: ubuntu-latest
    outputs:
      newer_version: ${{ steps.get-latest-version.outputs.newer_version }}
      latest_release: ${{ steps.get-latest-version.outputs.latest_release }}
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Get the latest Xray version
        id: get-latest-version
        env:
          OWNER: XTLS
          REPO: Xray-core
        run: |
          LATEST_RELEASE="$(
            curl -fsSL \
              -H "Accept: application/vnd.github+json" \
              "https://api.github.com/repos/$OWNER/$REPO/releases/latest" |
              jq -r '.tag_name'
          )"
          [[ -n "$LATEST_RELEASE" ]] || (echo "LATEST_RELEASE variable is empty" && exit 1)
          NEW_VERSION="$(echo $LATEST_RELEASE | cut -c 2-)"
          OLD_VERSION="$(grep "Latest version:" ./README.md | awk -F '/' '{print $NF}' | awk -F '-' '{print $2}')"
          if [[ "$NEW_VERSION" == "$OLD_VERSION" ]]; then
            echo "No updates needed"
            echo "Current version: V$OLD_VERSION"
            echo "::set-output name=newer_version::false"
            NEWER_VERSION=false
          else
            echo "Newer version available: $NEW_VERSION"
            echo "::set-output name=newer_version::true"
            NEWER_VERSION=true
          fi
          echo "Latest version is $LATEST_RELEASE"
          echo "LATEST_RELEASE=$LATEST_RELEASE" >> "$GITHUB_ENV"
          echo "latest_release=$LATEST_RELEASE" >> "$GITHUB_OUTPUT"
          echo "NEWER_VERSION=$NEWER_VERSION" >> "$GITHUB_ENV"
          echo "newer_version=$NEWER_VERSION" >> "$GITHUB_OUTPUT"

      # Install the cosign tool except on PR
      # https://github.com/sigstore/cosign-installer
      #- name: Install cosign
        #if: github.event_name != 'pull_request'
        #uses: sigstore/cosign-installer@59acb6260d9c0ba8f4a2f9d9b48431a222b68e20 #v3.5.0
        #with:
          #cosign-release: 'v2.2.4'

      # Set up BuildKit Docker container builder to be able to build
      # multi-platform images and export cache
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        if: steps.get-latest-version.outputs.newer_version == 'true'
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into GHCR ${{ env.REGISTRY }}
        #if: github.event_name != 'pull_request
        if: steps.get-latest-version.outputs.newer_version == 'true'
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log into Docker Hub ${{ env.REGISTRY }}
        #if: github.event_name != 'pull_request'
        if: steps.get-latest-version.outputs.newer_version == 'true'
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      #- name: Extract Docker metadata
        #id: meta
        #uses: docker/metadata-action@96383f45573cb7f253c731d3b3ab81c87ef81934 # v5.0.0
        #with:
          #images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

        
      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        if: steps.get-latest-version.outputs.newer_version == 'true'
        id: build-and-push
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/${{ github.repository }}:${{ env.LATEST_RELEASE }}
            ghcr.io/${{ github.repository }}:latest
            docker.io/${{ github.repository }}:${{ env.LATEST_RELEASE }}
            docker.io/${{ github.repository }}:latest
          #labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            XRAY_VERSION=${{ env.LATEST_RELEASE }}

      # Sign the resulting Docker image digest except on PRs.
      # This will only write to the public Rekor transparency log when the Docker
      # repository is public to avoid leaking data.  If you would like to publish
      # transparency data even for private images, pass --force to cosign below.
      # https://github.com/sigstore/cosign
      #- name: Sign the published Docker image
        #if: ${{ github.event_name != 'pull_request' }}
        #env:
          # https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-an-intermediate-environment-variable
          #TAGS: ${{ steps.meta.outputs.tags }}
          #DIGEST: ${{ steps.build-and-push.outputs.digest }}
        # This step uses the identity token to provision an ephemeral certificate
        # against the sigstore community Fulcio instance.
        #run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}

  update-readme:
    needs: build
    if: needs.build.outputs.newer_version == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Make update in README file
        run: |
          LATEST_RELEASE="${{ needs.build.outputs.latest_release }}"
          NEW_VERSION="$(echo $LATEST_RELEASE | cut -c 2-)"
          OLD_VERSION="$(grep "Latest version:" ./README.md | awk -F '/' '{print $NF}' | awk -F '-' '{print $2}')"
          if [[ "$NEW_VERSION" == "$OLD_VERSION" ]]; then
            echo "Maintainer version ($NEW_VERSION) is same as our current version ($OLD_VERSION)"
            echo "No changes needed."
          else
            sed -i "s|V-$OLD_VERSION-blue|V-$NEW_VERSION-blue|" README.md
            echo "Make an update in the README.md file"
            echo "Newer version is $NEW_VERSION"
          fi
      - name: Check for Changes
        id: check_changes
        run: |
          if [[ -n "$(git diff --exit-code)" ]]; then
            echo "Changes detected."
            echo "::set-output name=has_changes::true"
          else
            echo "No changes detected."
            echo "::set-output name=has_changes::false"
          fi
      - name: Commit and Push Changes
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          git commit -m 'Update version in README'
          git push
  
